//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempaApp.MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TempaApp.MyResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        internal static string Add_Device {
            get {
                return ResourceManager.GetString("Add Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string Application_Settings {
            get {
                return ResourceManager.GetString("Application Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to the wrong device.
        /// </summary>
        internal static string Attempting_to_connect_to_the_wrong_device {
            get {
                return ResourceManager.GetString("Attempting to connect to the wrong device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is off.
        /// </summary>
        internal static string Bluetooth_is_off {
            get {
                return ResourceManager.GetString("Bluetooth is off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string Connecting___ {
            get {
                return ResourceManager.GetString("Connecting...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to device.
        /// </summary>
        internal static string Connecting_to_device {
            get {
                return ResourceManager.GetString("Connecting to device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost.
        /// </summary>
        internal static string Connection_lost {
            get {
                return ResourceManager.GetString("Connection lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connection failed..
        /// </summary>
        internal static string Device_connection_failed_ {
            get {
                return ResourceManager.GetString("Device connection failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device settings.
        /// </summary>
        internal static string Device_settings {
            get {
                return ResourceManager.GetString("Device settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download and update your device with latest firmware?.
        /// </summary>
        internal static string Do_you_want_to_download_and_update_your_device_with_latest_firmware_ {
            get {
                return ResourceManager.GetString("Do you want to download and update your device with latest firmware?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error_ {
            get {
                return ResourceManager.GetString("Error!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the file.
        /// </summary>
        internal static string Error_while_saving_the_file {
            get {
                return ResourceManager.GetString("Error while saving the file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator couldn&apos;t be added to database.
        /// </summary>
        internal static string Indicator_couldn_t_be_added_to_database {
            get {
                return ResourceManager.GetString("Indicator couldn\'t be added to database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Unload.
        /// </summary>
        internal static string Load_Unload {
            get {
                return ResourceManager.GetString("Load Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load / Unload.
        /// </summary>
        internal static string Load_Unload_Page_Title_Text {
            get {
                return ResourceManager.GetString("Load Unload Page Title Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string Main_Page {
            get {
                return ResourceManager.GetString("Main Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your mobile device and your indicator has minimum %30 battery level!.
        /// </summary>
        internal static string Make_sure_your_mobile_device_and_your_indicator_has_minimum__30_battery_level_ {
            get {
                return ResourceManager.GetString("Make sure your mobile device and your indicator has minimum %30 battery level!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your mobile device has already connected to internet!.
        /// </summary>
        internal static string Make_sure_your_mobile_device_has_already_connected_to_internet_ {
            get {
                return ResourceManager.GetString("Make sure your mobile device has already connected to internet!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your mobile device is near your indicator!.
        /// </summary>
        internal static string Make_sure_your_mobile_device_is_near_your_indicator_ {
            get {
                return ResourceManager.GetString("Make sure your mobile device is near your indicator!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More_Page_Title_Text {
            get {
                return ResourceManager.GetString("More Page Title Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired.
        /// </summary>
        internal static string Paired {
            get {
                return ResourceManager.GetString("Paired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, turn on bluetooth of your mobile phone!.
        /// </summary>
        internal static string Please__turn_on_bluetooth_of_your_mobile_phone_ {
            get {
                return ResourceManager.GetString("Please, turn on bluetooth of your mobile phone!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prog. Rcp..
        /// </summary>
        internal static string Prog_Rcp_Disch {
            get {
                return ResourceManager.GetString("Prog Rcp Disch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe / Discharge Prog..
        /// </summary>
        internal static string Prog_Rcp_Page_Title_Text {
            get {
                return ResourceManager.GetString("Prog Rcp Page Title Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your device.
        /// </summary>
        internal static string Select_your_device {
            get {
                return ResourceManager.GetString("Select your device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected device is not suitable to communicate.
        /// </summary>
        internal static string Selected_device_is_not_suitable_to_communicate {
            get {
                return ResourceManager.GetString("Selected device is not suitable to communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Settings.
        /// </summary>
        internal static string Service_Settings {
            get {
                return ResourceManager.GetString("Service Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version.
        /// </summary>
        internal static string Software_version {
            get {
                return ResourceManager.GetString("Software version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Logs.
        /// </summary>
        internal static string Transaction_Logs {
            get {
                return ResourceManager.GetString("Transaction Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device.
        /// </summary>
        internal static string Unknown_device {
            get {
                return ResourceManager.GetString("Unknown device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update software.
        /// </summary>
        internal static string Update_software {
            get {
                return ResourceManager.GetString("Update software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string User_Settings {
            get {
                return ResourceManager.GetString("User Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning_ {
            get {
                return ResourceManager.GetString("Warning!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning_1 {
            get {
                return ResourceManager.GetString("Warning!1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device already has latest software version!.
        /// </summary>
        internal static string Your_device_already_has_latest_software_version_ {
            get {
                return ResourceManager.GetString("Your device already has latest software version!", resourceCulture);
            }
        }
    }
}
